### ISSUE TITLE
chr in #CHROM needed for GRCh37

### ISSUE THREAD

**Issue by clifflun** [BCM-Lupskilab/VizCNV#1]
Hi Haowie,

I came across this error

Warning: Error in h: error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': scanVcf: scanVcf: scanTabix: 'chr2' not present in tabix index

When I look at the vcf.gz file, the #CHROM column does not contain "chr". 

When I add "chr" back to each line (eg 2 -> chr2), vizCNV will plot normally

thanks

**Comment by cluhaowie** [comment]
Hi cliff,

thank you for submitting the issue. 
The difference of chromosome names in hg19 and GRCh37 causes such a problem. 
I have included a line to check the naming before grabbing the variant from the snp vcf file. This should fix the problem.
-Haowei
